GET http://localhost:3000/contacts

###
POST http://localhost:3000/contacts
Content-Type: application/json

{
    "name": "yash",
    "dob": "06/22/1999",
    "phoneNumbers": [
        9283849903,
        2938480923
    ],
    "emails": [
        "asdfjk@gmail.com",
        "asdflkjl@gmail.com"
    ]
}


###
PATCH http://localhost:3000/contacts/5ecf74e0825bf80d7409a455
Content-Type: application/json

{
    "name": "ajay",
    "dob" : "01/22/1999"
}

###
DELETE http://localhost:3000/contacts/5ecf74e0825bf80d7409a455


###
GET http://localhost:3000/contacts/5ecf95d290bdbc29e8a0fb06